runtime: python39 
instance_class: F1 # Basic instance class, eligible for free tier

entrypoint: gunicorn -b :$PORT main:app

# Automatic scaling settings
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0 # Can scale down to 0 to save costs (longer cold starts)
  max_instances: 1 # Start with 1, increase if needed

# Handlers tell App Engine how to route requests
handlers:
# Serve static files (CSS, JS, images) from the 'static' directory
- url: /static
  static_dir: static

# Route all other requests to Flask app script
- url: /.*
  script: auto
